lab1
raccoon1619/SPP pull request #1
Opened 2020-05-07 17:55 UTC by raccoon1619

2020-05-09 07:37 UTC, DmitryGolubko requested changes
Сделайте редіректы

2020-05-09 07:37 UTC, DmitryGolubko commented on lab1/index.js
> +    var data = fs.readFileSync("notes.json", "utf8");
В следующих лабораторных подключите базу.

2020-05-09 07:37 UTC, DmitryGolubko commented on lab1/index.js
> +app.post("/applyEdit/:noteId", urlencodedParser, function(request, response) {
Во второй лабораторной обратите внимание на роутинг. Про best practices можете почитать [тут](https://habr.com/ru/post/351890/). Буду обращать на это внимание.

2020-05-09 07:37 UTC, DmitryGolubko commented on lab1/index.js
> +        response.render("index", {
После обработки апдейта, удаления записи, необходимо делать редирект на index ресурс. Об этом можете почитать [здесь](https://ilyabirman.ru/meanwhile/all/web-developers-golden-rule/) і [здесь](https://habr.com/ru/post/86258/)

2020-05-10 08:13 UTC, raccoon1619 commented on lab1/index.js
> +        response.render("index", {
Сделала

2020-05-11 15:42 UTC, DmitryGolubko approved these changes
Принято

2020-07-05 19:36 UTC, merged